Emacs. Первые шаги

<b>Дифирамбы</b>

Без восхищения Емаксом не обходится ни одна статья о нем, но я буду
краток - он просто лучший и в нем есть все. Это все очень удобно
настраивается и в этой серии статей я покажу как превратить
стандартный Емакс в удобную операционную систему для работы.

<b>Непохожесть</b>

Первоначально, когда вы открываете только что установленный Емакс он
выглядит очень необычно - отсутствие привычных элементов управления
пугает. Зато потом, по мере понимания его философии вы понимаете,
здесь все иначе, но все - правильно!

<b>Установка</b>

На debian и ubuntu linux установка производится одной командой:

<code>sudo apt-get install emacs</code>

В других случаях читайте официальные рекомендации по установке.
* Начало работы
Чтобы начать работать с Емаксом нужно знать три вещи:
<pre>
| Как из него выйти  | C-x C-x |
| Как открыть файл   | C-x C-f |
| Как сохранить файл | C-x C-s |</pre>
Что значат эти обозначения во второй колонке? Это последовательность
нажатий клавиш С-x значить Ctrl+x, т.е. удерживая "Control", нажать
"x". Пробел между комбинациями - отпустить все клавиши. Т.е. 
комбинация C-x C-s это нажать Ctrl-x, отпустить, потом нажать Ctrl+s

Дальше будет веселее - оставайтесь с нами!
